name: Demo-Workflow

on:
  push:
    branches:
    - main

jobs:
  demo:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Run a simple script
      - run: echo "Hello from the cli"
      - uses: actions/checkout@v5
      - run: pwd && ls -al
      - name: Configure GO
      - uses: actions/setup-go@v5
      - run: go version
      - name: Demo GH CLI Commands
      - run: env
      - run: |
          gh --version
          gh auth status
          gh repo list
